# TODO: Testing with multiple database backends. By default,
# ArchivesSpace will run these tests against the embedded Derby database
# (see config/config-distribution.rb). To investigate this see 
# http://about.travis-ci.org/docs/user/database-setup/

language: ruby

rvm:
  # The bootstrap script installs jruby, so this setting does not matter.
  - jruby-19mode

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

env: INTEGRATION_LOGFILE=/var/tmp/aspace-integration.log


before_script:
  # http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 

branches:
  only:
    - master

script:
  - build/run bootstrap
  - build/run backend:test
  - build/run backend:integration
# - build/run common:test  # https://github.com/hudmol/archivesspace/commit/193fe9a3990da74e37e98140c9eaa264ec801643#L0R106
  - SCREENSHOT_ON_ERROR=1 build/run selenium:test
  - WITH_NODEJS=1 build/run dist

after_failure:
  - build/run dump-file -Ddump.file=/var/tmp/aspace-integration.log

notifications:
  irc: "irc.freenode.org#archivesspace"
  # don't send email for now, until we know who we want to receive it
  email: false
