language: java
jdk:
- oraclejdk8
matrix:
  fast_finish: true
env:
  global:
  - INTEGRATION_LOGFILE=/var/tmp/aspace-integration.log
  - DISPLAY=:99.0
  - SCREENSHOT_ON_ERROR=1
  matrix:
  - DB=mysql TASK=travis:test
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=1"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=2"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=3"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=4"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=5"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=6"
  - DB=mysql TASK=travis:selenium:public
  - TASK=dist
before_install:
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 2560x1700x24
- export DISPLAY=:99.0
before_script:
- (cd /tmp; wget 'https://ftp.mozilla.org/pub/firefox/releases/47.0.1/linux-x86_64/en-US/firefox-47.0.1.tar.bz2'; tar xvjf firefox-47.0.1.tar.bz2)
- sleep 3
- if [[ "$DB" == "mysql" ]]; then (mkdir lib; cd lib; curl -Oq http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar );
  fi
- if [[ "$DB" == "mysql" ]]; then export JAVA_OPTS="-Daspace.config.db_url=jdbc:mysql://localhost:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=root";
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database archivesspace default
  character set utf8;"; fi
- 'export JAVA_OPTS="-Xmx600m -verbose:gc $JAVA_OPTS"'
- 'export PATH="/tmp/firefox:$PATH"'
- firefox --version
branches:
  except:
  - gh-pages
script:
- build/run $TASK $TASK_OPTS
notifications:
  irc: irc.freenode.org#archivesspace
  email: false
addons:
  artifacts:
    debug: true
    bucket: astravisartifacts 
    paths:
    - $( ls /var/tmp/*.png | tr "\n" ":" )
    - $( ls /tmp/*.png | tr "\n" ":" )
    - $( ls /var/tmp/*.html | tr "\n" ":" )
    - $( ls /var/log/mysql/* | tr "\n" ":" )
    - $( ls  /var/tmp/aspace-integration.log | tr "\n" ":" )
sudo: false
after_failure:
- if [[ -e "/tmp/firefox_console" ]]; then cat /tmp/firefox_console; fi
