language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
matrix:
  fast_finish: true
env:
  global:
  - INTEGRATION_LOGFILE=/var/tmp/aspace-integration.log
  - SCREENSHOT_ON_ERROR=1
  - SELENIUM_CHROME=true
  matrix:
  - DB=mysql TASK=travis:test
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=1"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=2"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=3"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=4"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=5"
  - DB=mysql TASK=travis:selenium:staff TASK_OPTS="-Dcores=6 -Dgroups=6"
  - TASK=dist
before_install:
- cat /etc/hosts # Fix buffer overflow in getLocalHostName of OpenJDK 6/7 by shortening the host name
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
- sudo mv /tmp/hosts /etc/hosts
- cat /etc/hosts
install:
- wget -N http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
- chromedriver -v
before_script:
- free -m
- sleep 3
- if [[ "$DB" == "mysql" ]]; then (mkdir lib; cd lib; curl -Oq http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar );
  fi
- if [[ "$DB" == "mysql" ]]; then export JAVA_OPTS="-Daspace.config.db_url=jdbc:mysql://localhost:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=root";
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database archivesspace default
  character set utf8;"; fi
- 'export JAVA_OPTS="-Xmx1024m -verbose:gc $JAVA_OPTS"'
branches:
  except:
  - gh-pages
script:
- build/run $TASK $TASK_OPTS
notifications:
  email: false
bundler_args: --retry 5
addons:
  chrome: stable
  artifacts:
    debug: true
    bucket: aspacetravisartifacts
    paths:
    - $( ls /var/tmp/*.png | tr "\n" ":" )
    - $( ls /tmp/*.png | tr "\n" ":" )
    - $( ls /var/tmp/*.html | tr "\n" ":" )
    - $( ls /var/log/mysql/* | tr "\n" ":" )
    - $( ls  /var/tmp/aspace-integration.log | tr "\n" ":" )
sudo: true
after_failure:
- dmesg | tail -500
