name: Common Tests
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: Java version to run specs on
        required: true
        type: choice
        options:
          - '11'
          - '17'
        default: '17'

  workflow_call:
    inputs:
      java-version:
        description: Java version to run specs on
        required: true
        type: string
        default: '17'

jobs:
  backend:
    name: Common_Java_v${{ inputs.java-version || 17 }} # https://archivesspace.atlassian.net/browse/ANW-2022
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version || 17 }} # https://archivesspace.atlassian.net/browse/ANW-2022
        distribution: temurin

    - uses: './.github/actions/bootstrap'
      with:
        backend: true
        indexer: true

    - name: Run Common tests
      run: |
        ./build/run common:test
      env:
        ARCHIVESSPACE_VERSION: ${{ github.ref }}

    - name: Post Coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        format: simplecov
        compare-ref: ${{ github.event.repository.default_branch }}
        flag-name: common
        debug: false
        parallel: true
