name: Public Testing

on:
  pull_request:
    paths:
      - '.github/workflows/public.yml'
      - 'public/**'
      - 'common/**'
      - 'solr/**'

jobs:
  public:
    name: Public
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        java: [ 8, 11 ]

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: archivesspace
          MYSQL_USER: as
          MYSQL_PASSWORD: as123
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      db-accessibility:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: accessibility
          MYSQL_USER: as
          MYSQL_PASSWORD: as123
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Allow ArchivesSpace functions for app db user
      env:
        DB_PORT: ${{ job.services.db.ports[3306] }}
        DB_ACCESSIBILITY_PORT: ${{ job.services.db-accessibility.ports[3306] }}
      run: |
        mysql --host 127.0.0.1 --port $DB_PORT -uroot -proot -e "SET GLOBAL log_bin_trust_function_creators = 1;"
        mysql --host 127.0.0.1 --port $DB_ACCESSIBILITY_PORT -uroot -proot accessibility < build/mysql_db_fixtures/accessibility.sql

    - name: Bootstrap ArchivesSpace
      run: |
        ./build/run bootstrap
        wget -P ./common/lib https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.23/mysql-connector-java-8.0.23.jar

    - name: Run Public tests
      env:
        ASPACE_TEST_DB_URL: jdbc:mysql://127.0.0.1:${{ job.services.db.ports[3306] }}/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123&useSSL=false&allowPublicKeyRetrieval=true
      run: |
        ./build/run public:test

    - name: Run Public accessibility tests
      env:
        ASPACE_TEST_DB_URL: jdbc:mysql://127.0.0.1:${{ job.services.db-accessibility.ports[3306] }}/accessibility?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123&useSSL=false&allowPublicKeyRetrieval=true
      run: |
        ./build/run public:test:accessibility
