name: Stats
on:
  schedule:
    - cron: "0 5 1 * *"
  push:
    branches:
      - '_fetches-download-stats-on-push'
jobs:
  append:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11' # https://archivesspace.atlassian.net/browse/ANW-2022

      - name: Get download stats and append
        run: |
          ./build/run thor -Dtask="stats:download"

      - name: Commit files
        run: |
          git config --local user.name "archivesspace"
          git add ./track-release-downloads.csv
          git commit -m "Updating the download stats"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
